---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  hiera_data_path: hieradata
  require_chef_for_busser: false

platforms:
  - name: centos-6.6-64-nocm
    driver_config:
      box: puppetlabs/centos-6.6-64-nocm
#  - name: puppetlabs/centos-7.0-64-nocm
#    driver_config:
#      box: puppetlabs/centos-7.0-64-nocm
#  - name: puppetlabs/ubuntu-14.04-64-nocm
#    driver_config:
#      box: puppetlabs/ubuntu-14.04-64-nocm
#  - name: debian-7.8-64-nocm
#		driver_plugin: vagrant
#    driver_config:
#      box: debian-7.8-64-nocm

suites:
  - name: omd
    manifests: site.pp
    driver:
      vm_hostname: omd
      network:
        - ["forwarded_port", {guest: 80, host: 4567}]

verifier:
  ruby_bindir: '/usr/bin'
